services:
  rate-api:
    image: tripladev/rate-api
    ports:
      - "8080:8080"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  prometheus-exporter:
    build: .
    command: bundle exec prometheus_exporter --bind 0.0.0.0 --port 9394
    ports:
      - "9394:9394"
    volumes:
      - .:/rails
    environment:
      - CACHE_PROVIDER_TYPE=redis
      - REDIS_URL=redis://redis:6379/0
      - RAILS_LOG_TO_STDOUT=true
    depends_on:
      - redis

  interview-dev:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    environment:
      - RATE_API_URL=http://rate-api:8080
      - PROMETHEUS_COLLECTOR_URL=http://prometheus-exporter:9394
      - CACHE_PROVIDER_TYPE=redis
      - REDIS_URL=redis://redis:6379/0
      - RAILS_LOG_TO_STDOUT=true
    depends_on:
      - rate-api
      - prometheus-exporter
      - redis

  scheduler:
    build: .
    command: sh -c "while true; do bundle exec rake rates:refresh; sleep 240; done"
    restart: always
    volumes:
      - .:/rails
    environment:
      - RATE_API_URL=http://rate-api:8080
      - PROMETHEUS_COLLECTOR_URL=http://prometheus-exporter:9394
      - CACHE_PROVIDER_TYPE=redis
      - REDIS_URL=redis://redis:6379/0
      - RAILS_LOG_TO_STDOUT=true
    depends_on:
      - rate-api
      - prometheus-exporter
      - redis
